---
title: "課?<a0>?練習模<e7><89><88>"
author: "Cheng"
date: "2020-12-23"
output: output_format
params:
  id: "410973024"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
# Given some information
R <- 0.09
M <- 10000
T <- 3
# What I need to do
PDV <- 
{
  M/(1+R)**T
}
```
```{r}
getPDV <- function(R,M,T) 
{
  M/(1+R)**T
}
```
```{r}
getPDV(R=0.09, T=3, M=10000)
```
```{r}
debug(getPDV) 
getPDV(R=0.09, T=3, M=10000) 
undebug(getPDV)

```
```{r}
# Given some information
TT <- 3
# What I need to do
getPDV2 <- function(R,M){
  M/(1+R)**TT
}
```
```{r}
getPDV2(R=0.12, M=50000)
debug(getPDV2)
getPDV2(R=0.12, M=50000)
undebug(getPDV2)
```
```{r}
testFun <- function(){
  a <-2
  b <- 5
  a+b
}
testFun()
```
```{r}
testErrorFun <- function(){
  a <-2
  b <- 5
  output <- a+b
}
testErrorFun()
```
```{r}
testFun <- function(){
  a <-2
  b <- 5
  return(a+b)
}
testFun()
```


```{r}
testFun <- function(){
  a <-2
  b <- 5
  invisible(a+b)
}
testFun()
output <- testFun()
output
```
```{r}
demandFun <- function(P) 5-3*P
supplyFun <- function(P) 1+0.5*P
market <- list(
  demand=demandFun,
  supply=supplyFun
)
```
```{r}
df0 <- function(f){
  epsilon <- 0.00001
  (f(epsilon)-f(0))/epsilon
}

df0(market$demand)
df0(market$supply)
```
```{r}
userBirthday <- ymd("1998-10-30")

userHoroscopes <- 
  {
    # 取得生日年份
    birthYear <- {
      
    }
    
    # 取得生日年份的12星座起始日期
    horoscopeStartingDateInBirthYear <- {
      
    }
    
    # 切割生日成為12星座區間
    cutBirthdayByStartingDate <- {
      
    }
    
    # 改變星座區間類別名稱
    birthdayCutRenameLevels <- {
      
    }
    levels(cutBirthdayByStartingDate) <- birthdayCutRenameLevels
    
    as.character(cutBirthYearByStartingDate)
  }
```
```{r}
get_userHoroscopes(ymd("1995-08-27"))
get_userHoroscopes(ymd("1970-05-18"))
get_userHoroscopes(ymd("2001-4-1"))
```
```{r}
get_userHoroscopes2 <- function(userBirthday){
  assertthat::assert_that(is.Date(userBirthday),
                          msg="userBirthday should be a Date class object.")
  get_userHoroscopes(userBirthday)
}
```
```{r}
df0 <- function(f, epsilon=0.00001){
  (f(epsilon)-f(0))/epsilon
}
```
```{r}
myFun <- function(x){
  5*x^2-2*x+7
}
```
```{r}
df0(myFun)
```
```{r}
df0(myFun, epsilon = 1e-08)
df0(myFun, epsilon = 1e-10)
```

```{r}

```

