---
title: "課?<a0>?練習模<e7><89><88>"
author: "Cheng"
date: "2020-10-28"
output: output_format
params:
  id: "410973024"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
vectorExample <- c("小明", "小英", "大雄")

# 有多少位置可選：
length(vectorExample)
```
```{r}
vectorExample[[1]]
vectorExample[[3]]
```
```{r}
listExample <- list(student = "小明", 學期 = list(`108-1` = list(list(name = "個體經濟學", 
    teacher = "Alice", grade = 85)), `108-2` = list(list(name = "總體經濟學", 
    teacher = "Mark", grade = 78))))
# 有多少位置可選：
length(listExample)
```


```{r}
listExample[[1]]
listExample[[2]]
```
```{r}
# 顯示到第一層
str(listExample, max.level = 1)

listExample[c(1, 2)]
```


```{r}
# 顯示到第一層
str(listExample, max.level = 1)

listExample[c("學期")]
listExample[c("student", "學期")]
```


```{r}
vectorExample
vectorExample[c(T, T, F)]  # 要，要，不要
```
```{r}
pickByNumber <- c(1,3)
pickByName <- c("p1",p3)
c(T,F,T) -> pickByLogical
```


```{r}
vevtorxamplesBy

```
```{r}
numVector <- c(2, 3, 6, -1, 4, 2, 6)
select1 <- numVector[c(1,4)]
select1
```


```{r}
today <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))
tomorrow <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))

weather <- list(today, tomorrow)

print(weather)
```


```{r}
weather[[1]][[2]][[2]]  # 今天/新北市/highest_temp
weather[[2]][[2]][[2]]  # 明天/新北市/highest_temp
```
```{r}
```


```{r}
```

